# Generated by Django 4.1.7 on 2023-02-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('repo1', models.CharField(blank=True, max_length=100, null=True)),
                ('repo2', models.CharField(blank=True, max_length=100, null=True)),
                ('web', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
